const word = [
    { word: "Algorithm", hint: "A step-by-step procedure for calculations." },
    { word: "API", hint: "Interface that allows software applications to communicate." },
    { word: "Bandwidth", hint: "The amount of data that can be transmitted in a given time." },
    { word: "Blockchain", hint: "A decentralized digital ledger of transactions." },
    { word: "Cloud Computing", hint: "Using remote servers to store, manage, and process data." },
    { word: "Cryptocurrency", hint: "Digital or virtual currency that uses cryptography for security." },
    { word: "Data Mining", hint: "The process of discovering patterns in large datasets." },
    { word: "Encryption", hint: "Converting information into a secure format." },
    { word: "Firewall", hint: "A network security system that monitors and controls incoming and outgoing traffic." },
    { word: "Firmware", hint: "Permanent software programmed into a device's hardware." },
    { word: "GPU", hint: "A processor designed for handling graphics and computations." },
    { word: "HTML", hint: "The standard language for creating web pages." },
    { word: "IoT", hint: "Network of interconnected devices embedded with sensors." },
    { word: "JavaScript", hint: "A programming language used to create interactive effects within web browsers." },
    { word: "Kernel", hint: "The core component of an operating system." },
    { word: "Machine Learning", hint: "Algorithms that improve through experience." },
    { word: "Network", hint: "A group of interconnected computers sharing resources." },
    { word: "Operating System", hint: "Software that manages computer hardware and software." },
    { word: "Protocol", hint: "A set of rules governing data transmission." },
    { word: "Quantum Computing", hint: "Computing using quantum-mechanical phenomena." },
    { word: "Router", hint: "A device that forwards data packets between computer networks." },
    { word: "Software", hint: "Programs and other operating information used by a computer." },
    { word: "Token", hint: "A unit of value issued by a project, often used in blockchain systems." },
    { word: "UI/UX", hint: "User Interface/User Experience design focuses on the interaction between users and products." },
    { word: "Virtual Reality", hint: "Computer-generated simulation of a three-dimensional environment." },
    { word: "Wi-Fi", hint: "Wireless networking technology that uses radio waves to provide high-speed internet." },
    { word: "XSS", hint: "A vulnerability in web applications where attackers inject malicious scripts." },
    { word: "YAML", hint: "A human-readable data serialization standard." },
    { word: "Zip", hint: "A file format used for data compression." },
    { word: "API Gateway", hint: "A server that acts as an API front-end, handling requests." },
    { word: "Big Data", hint: "Extremely large datasets analyzed computationally to reveal patterns." },
    { word: "Cloud Storage", hint: "Storing data on remote servers accessible via the internet." },
    { word: "DevOps", hint: "A set of practices combining software development and IT operations." },
    { word: "Edge Computing", hint: "Processing data closer to its source to reduce latency." },
    { word: "Firewall", hint: "A system designed to prevent unauthorized access to or from a network." },
    { word: "Git", hint: "A version control system for tracking changes in source code." },
    { word: "Hacker", hint: "A person who gains unauthorized access to computer systems." },
    { word: "IoT", hint: "Internet of Things; devices interconnected through the internet." },
    { word: "JIT Compiler", hint: "Just-In-Time compiler that compiles code during execution." },
    { word: "Kubernetes", hint: "An open-source platform for managing containerized applications." },
    { word: "Load Balancer", hint: "Distributes network or application traffic across multiple servers." },
    { word: "Malware", hint: "Malicious software designed to damage or disrupt systems." },
    { word: "NLP", hint: "Natural Language Processing; enables computers to understand human language." },
    { word: "Open Source", hint: "Software with source code that anyone can inspect, modify, and enhance." },
    { word: "Phishing", hint: "A type of cyber attack where attackers deceive users into providing sensitive information." },
    { word: "Quantum Bits (Qubits)", hint: "The basic unit of quantum information in quantum computing." },
    { word: "Router", hint: "Device that routes data from the internet to your local network." },
    { word: "Server", hint: "A system that provides resources, services, or data to other computers." },
    { word: "Tokenization", hint: "The process of converting sensitive data into a unique identifier." },
    { word: "VPN", hint: "Virtual Private Network; a service that encrypts your internet connection to secure data." }
];
